provider "aws" {
  #  use aws profile for iam access keys
  region = "${var.region}"
  profile = "${var.terra-profile}"
assume_role {
    role_arn = "${var.role_arn}"
    session_name = "${var.role_session_name}"
  }
}

module "snow-asgroup" {
  source = "./snow-asgroup"
  "AmiId" = "${var.AmiId}"
  "AmiDistro" = "${var.AmiDistro}"
  "AppScriptParams" = "${var.AppScriptParams}"
  "AppScriptShell" = "${var.AppScriptShell}"
  "AppScriptUrl" = "${var.AppScriptUrl}"
  "AppVolumeDevice" = "${var.AppVolumeDevice}"
  "AppVolumeMountPath" = "${var.AppVolumeMountPath}"
  "AppVolumeSize" = "${var.AppVolumeSize}"
  "AppVolumeType" = "${var.AppVolumeType}"
  "CfnBootstrapUtilsUrl" = "${var.CfnBootstrapUtilsUrl}"
  "CfnEndpointUrl" = "${var.CfnEndpointUrl}"
  "CfnGetPipUrl" = "${var.CfnGetPipUrl}"
  "CloudWatchLogsAgentUrl" = "${var.CloudWatchLogsAgentUrl}"
  "CloudWatchLogsConfigUrl" = "${var.CloudWatchLogsConfigUrl}"
  "CloudWatchLogsInstallUrl" = "${var.CloudWatchLogsInstallUrl}"
  "InstanceRole" = "${var.InstanceRole}"
  "InstanceType" = "${var.InstanceType}"
  "KeyPairName" = "${var.KeyPairName}"
  "NoPublicIp" = "${var.NoPublicIp}"
  "NoReboot" = "${var.NoReboot}"
  "NoUpdates" = "${var.NoUpdates}"
  "PuppetInstallScriptUrl" = "${var.PuppetInstallScriptUrl}"
  "PuppetMasterIp" = "${var.PuppetMasterIp}"
  "PuppetEnvironment" = "${var.PuppetEnvironment}"
  "PuppetAgentRpm" = "${var.PuppetAgentRpm}"
  "SecurityGroupIds" = "${var.SecurityGroupIds}"
  "ServiceNowInstallScript" = "${var.ServiceNowInstallScript}"
  "ServiceNowInstallTimeout" = "${var.ServiceNowInstallTimeout}"
  "ServiceNowJarZipUrl" = "${var.ServiceNowJarZipUrl}"
  "SubnetIds" = "${var.SubnetIds}"
  "RdsEndpointAddress" = "${var.RdsEndpointAddress}"
  "RdsDbUsername" = "${var.RdsDbUsername}"
  "RdsDbPassword" = "${var.RdsDbPassword}"
  "stackname" = "${var.stackname}"
  "s3bucket" = "${var.s3bucket}"
  "local-exec-profile" = "${var.local-exec-profile}"
  }
