provider "aws" {
  #  use aws profile for iam access keys
  region = "${var.region}"
  profile = "${var.terra-profile}"
assume_role {
    role_arn = "${var.role_arn}"
    session_name = "${var.role_session_name}"
  }
}

module "snow-asgroup" {
  source = "./snow-asgroup"
  "AmiId" = "${var.AmiId}"
  "AmiDistro" = "${var.AmiDistro}"
  "AppScriptParams" = "${var.AppScriptParams}"
  "AppScriptShell" = "${var.AppScriptShell}"
  "AppScriptUrl" = "${var.AppScriptUrl}"
  "AppVolumeDevice" = "${var.AppVolumeDevice}"
  "AppVolumeMountPath" = "${var.AppVolumeMountPath}"
  "AppVolumeSize" = "${var.AppVolumeSize}"
  "AppVolumeType" = "${var.AppVolumeType}"
  "CfnBootstrapUtilsUrl" = "${var.CfnBootstrapUtilsUrl}"
  "CfnEndpointUrl" = "${var.CfnEndpointUrl}"
  "CfnGetPipUrl" = "${var.CfnGetPipUrl}"
  "CloudWatchAgentUrl" = "${var.CloudWatchAgentUrl}"
  "DesiredCapacity" = "${var.DesiredCapacity}"
  "InstanceRole" = "${var.InstanceRole}"
  "InstanceType" = "${var.InstanceType}"
  "KeyPairName" = "${var.KeyPairName}"
  "MaxCapacity" = "${var.MaxCapacity}"
  "MinCapacity" = "${var.MinCapacity}"
  "NoPublicIp" = "${var.NoPublicIp}"
  "NoReboot" = "${var.NoReboot}"
  "NoUpdates" = "${var.NoUpdates}"
  "PypiIndexUrl" = "${var.PypiIndexUrl}"
  "RdsEndpointAddress" = "${var.RdsEndpointAddress}"
  "RdsDbUsername" = "${var.RdsDbUsername}"
  "RdsDbPassword" = "${var.RdsDbPassword}"
  "ScaleDownSchedule" = "${var.ScaleDownSchedule}"
  "ScaleUpSchedule" = "${var.ScaleUpSchedule}"
  "SecurityGroupIds" = "${var.SecurityGroupIds}"
  "ServiceNowInstallScript" = "${var.ServiceNowInstallScript}"
  "ServiceNowInstallTimeout" = "${var.ServiceNowInstallTimeout}"
  "ServiceNowJarZipUrl" = "${var.ServiceNowJarZipUrl}"
  "SubnetIds" = "${var.SubnetIds}"
  "ToggleCfnInitUpdate" = "${var.ToggleCfnInitUpdate}"
  "ToggleNewInstances" = "${var.ToggleNewInstances}"
  "WatchmakerAdminGroups" = "${var.WatchmakerAdminGroups}"
  "WatchmakerAdminUsers" = "${var.WatchmakerAdminUsers}"
  "WatchmakerConfig" = "${var.WatchmakerConfig}"
  "WatchmakerEnvironment" = "${var.WatchmakerEnvironment}"
  "WatchmakerOuPath" = "${var.WatchmakerOuPath}"
  "stackname" = "${var.stackname}"
  "s3bucket" = "${var.s3bucket}"
  "local-exec-profile" = "${var.local-exec-profile}" 
  }
