resource "aws_cloudformation_stack" "snowasg" {
  name = "${var.stackname}"

  parameters {
  "AmiId" = "${var.AmiId}"
  "AmiDistro" = "${var.AmiDistro}"
  "AppScriptParams" = "${var.AppScriptParams}"
  "AppScriptShell" = "${var.AppScriptShell}"
  "AppScriptUrl" = "${var.AppScriptUrl}"
  "AppVolumeDevice" = "${var.AppVolumeDevice}"
  "AppVolumeMountPath" = "${var.AppVolumeMountPath}"
  "AppVolumeSize" = "${var.AppVolumeSize}"
  "AppVolumeType" = "${var.AppVolumeType}"
  "CfnBootstrapUtilsUrl" = "${var.CfnBootstrapUtilsUrl}"
  "CfnEndpointUrl" = "${var.CfnEndpointUrl}"
  "CfnGetPipUrl" = "${var.CfnGetPipUrl}"
  "CloudWatchAgentUrl" = "${var.CloudWatchAgentUrl}"
  "CloudWatchLogsAgentUrl" = "${var.CloudWatchLogsAgentUrl}"
  "CloudWatchLogsConfigUri" = "${var.CloudWatchLogsConfigUri}"
  "CloudWatchLogsInstallUri" = "${var.CloudWatchLogsInstallUri}"
  "DesiredCapacity" = "${var.DesiredCapacity}"
  "InstanceRole" = "${var.InstanceRole}"
  "InstanceType" = "${var.InstanceType}"
  "KeyPairName" = "${var.KeyPairName}"
  "LogGroupName" = "${var.LogGroupName}"
  "MaxCapacity" = "${var.MaxCapacity}"
  "MinCapacity" = "${var.MinCapacity}"
  "NoPublicIp" = "${var.NoPublicIp}"
  "NoReboot" = "${var.NoReboot}"
  "NoUpdates" = "${var.NoUpdates}"
  "PypiIndexUrl" = "${var.PypiIndexUrl}"
  "RdsEndpointAddress" = "${var.RdsEndpointAddress}"
  "RdsDbUsername" = "${var.RdsDbUsername}"
  "RdsDbPassword" = "${var.RdsDbPassword}"
  "ScaleDownSchedule" = "${var.ScaleDownSchedule}"
  "ScaleUpSchedule" = "${var.ScaleUpSchedule}"
  "SecurityGroupIds" = "${var.SecurityGroupIds}, ${var.lb-tg-sg1}"
  "ServiceNowInstallScript" = "${var.ServiceNowInstallScript}"
  "ServiceNowInstallTimeout" = "${var.ServiceNowInstallTimeout}"
  "ServiceNowJarZipUri" = "${var.ServiceNowJarZipUri}"
  "SubnetIds" = "${var.SubnetIds}"
  "ToggleCfnInitUpdate" = "${var.ToggleCfnInitUpdate}"
  "ToggleNewInstances" = "${var.ToggleNewInstances}"
  "WatchmakerAdminGroups" = "${var.WatchmakerAdminGroups}"
  "WatchmakerAdminUsers" = "${var.WatchmakerAdminUsers}"
  "WatchmakerConfig" = "${var.WatchmakerConfig}"
  "WatchmakerEnvironment" = "${var.WatchmakerEnvironment}"
  "WatchmakerOuPath" = "${var.WatchmakerOuPath}"
   }

template_url = "${var.SnowAsgTemplateUrl}"
}